### ISSUE TITLE
Unable to iterate over elements to render list.

### ISSUE THREAD

**Issue by ghost** [weisrc/swrf#1]
This is more of a question that a proper issue.
Is there a way to render out lists of elements?

I have tried the following:
![image](https://user-images.githubusercontent.com/108161206/202894215-94b6622d-263b-4de4-9acd-a8c372f3dafe.png)
With no result.

Thanks heaps!
Jayman.

**EDIT: I didn't read the docs properly... I have found the map function to do what I wanted! Cheers, that is my fault. Closing the issue now.**

**Comment by weisrc** [comment]
Feel free to open more issues if you encounter more!
